### ISSUE TITLE
Customizing the not enought argument message.

### ISSUE THREAD

**Issue by ghost** [BoxOfDevs/CommandUsage#1]
Hello. Where can I change the message "Invalid command syntax"? Thanks!

**Comment by Ad5001** [comment]
There is no known way to do it now.
If a way exists, it hasn't been discovered and so could not be added.
But if a way to do it is discovered, we'll definitivly add.

**Comment by ghost** [comment]
But the message must be somewhere or not?

**Comment by Vaults1** [comment]
It will be somewhere, it's in a place we don't currently know of yet.

**Comment by ghost** [comment]
:/

**Comment by Ad5001** [comment]
@lolmanz0 It **may** be somewhere. Note that this is a possibility, not a must. Thought no one found how to do this, we have no idea if that's even possible.

**Comment by ghost** [comment]
Okay, thanks.

**Comment by Ad5001** [comment]
It should still be open because it's an enhancement but it cannot be made yet and it's relevant.

**Comment by AvgZing** [comment]
Oh, kk

**Comment by Ad5001** [comment]
Btw I cannot talk on Discord because it's dowm (you will see it with the webhook).

**Comment by lavender-sys** [comment]
@TheRoyalBlock I found a way around the no chatting thing with himbeer.me/discord

**Comment by AvgZing** [comment]
@Ad5001 I realized that, see my latest tweet

**Comment by jasonw4331** [comment]
I believe the incorrect syntax message is client-side

**Comment by Ad5001** [comment]
Yes, but the overload command data can have a (non discovered) property which could change this message.

**Comment by AvgZing** [comment]
Technically you **could** have a double, so it appears as
Invalid command syntax
AND
Command syntax is incorrect, please use /help commandusage for more information.

in chat

**Comment by Ad5001** [comment]
No. Beause when the syntax error occurs, it does not send the command to the server.

**Comment by AvgZing** [comment]
oh.
